USE mybase;
CREATE TABLE remark
(
	IP VARCHAR(32) NOT NULL,
	user_name VARCHAR(32) NOT NULL,
	test_file VARCHAR(128) NOT NULL,
	update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
	up INT NOT NULL DEFAULT '0' COMMENT '点赞',
	down INT NOT NULL DEFAULT '0' COMMENT '点赞',
	limit_count INT NOT NULL DEFAULT '0' COMMENT '评论次数限制',
	remark_2 VARCHAR(32) NOT NULL COMMENT '空列表备用',
	PRIMARY KEY (IP)
)COMMENT '留言表';